pipeline {
    agent any
    environment {
            APP_NAME = "reddit-clone-pipeline"
        }
        stages {
            stage("Cleanup Workspace") {
                steps {
                    cleanWs()
                }
            }
            stage("Checkout from SCM") {
                steps {
                        git branch: 'main', credentialsId: 'github', url: 'https://github.com/faresalig/a-reddit-clone-gitops-project'
                }
            }
            stage("Update the Deployment Tags") {
                steps {
                    sh """
                        cat deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        cat deployment.yaml
                    """
                }
            }
            stage("Push the changed deployment file to Github.") {
                steps {
                    sh """
                        git config --global user.name "faresalig"
                        git config --global user.email "fares123456789ali@gmail.com"
                        git add deployment.yaml
                        git commit -m "Updated Deployment Manifest"
                    """
                    withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                        sh "git push https://github.com/faresalig/a-reddit-clone-gitops-project main"
                    }
                }
            }
    }
}
